"A date string with format `Y-m-d H:i:s`, e.g. `2018-01-01 13:00:00`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

"The `Upload` scalar type represents a file upload."
scalar Upload @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Upload")

"A user of the application."
type User {
    id: ID!
    name: String!
    email: String!
    role: Role! @belongsTo
    created_at: DateTime!
    updated_at: DateTime!
}

"An article written by a user."
type Article {
    id: ID!
    title: String!
    content: String!
    author: User! @belongsTo
    categories: [Category!] @belongsToMany
    images: [Image!]! @hasMany
    created_at: DateTime!
    updated_at: DateTime!
}

"A role for a user."
type Role {
    id: ID!
    name: String!
    slug: String!
}

"A category for an article."
type Category {
    id: ID!
    name: String!
    slug: String!
}

"An image for an article."
type Image {
    id: ID!
    path: String!
    created_at: DateTime!
    updated_at: DateTime!
}

"Defines the queries available to the client."
type Query {
    "Find all articles, paginated."
    articles: [Article!]! @paginate(defaultCount: 10)

    "Find all article by a specific user, paginated"
    articlesByUser(userID: ID! @eq(key: "author_id")): [Article!] @paginate(defaultCount: 10)

    "Find a user."
    user(id: ID! @eq): User @find @guard(with: ["sanctum"])

    "Me"
    me: User @auth

    "Get Article by Id"
    article(id: ID! @eq): Article @find

    "Get All Categories"
    getCategories: [Category!]! @all
}

"A token response for authentication."
type AuthPayload {
    token: String!
    user: User!
}


"Defines the mutations available to the client."
type Mutation {
    login(email: String!, password: String!): AuthPayload @field(resolver: "App\\GraphQL\\Mutations\\Login")

    createArticle(title: String!, content: String!, categoryIds: [ID!], images: [Upload!]): Article
    @field(resolver: "App\\GraphQL\\Mutations\\CreateArticle")
    @guard(with: ["sanctum", "admin"])
    @admin

    editArticle(id: ID!, title: String, content: String, categoryIds: [ID!]): Article
    @field(resolver: "App\\GraphQL\\Mutations\\EditArticle")
    @guard(with: ["sanctum", "admin"])
    @admin
}
