"A date string with format `Y-m-d H:i:s`, e.g. `2018-01-01 13:00:00`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

"The `Upload` scalar type represents a file upload."
scalar Upload @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Upload")

"A user of the application."
type User {
    id: ID!
    name: String!
    email: String!
    role: Role! @belongsTo
    articles(
        "Limit the number of articles returned."
        limit: Int @limit
        "Order the articles."
        orderBy: [OrderByClause!] @orderBy
    ): [Article!]! @hasMany
    comments(
        "Limit the number of comments returned."
        limit: Int @limit
        "Order the comments."
        orderBy: [OrderByClause!] @orderBy
    ): [Comment!]! @hasMany
    commentedArticles: [Article!]! @belongsToMany
    favoriteArticles: [Article!]! @belongsToMany(relation: "favoriteArticles")
    lastReadArticles: [Article!]! @belongsToMany(relation: "lastReadArticles")
    created_at: DateTime!
    updated_at: DateTime!
}

"An article written by a user."
type Article {
    id: ID!
    title: String!
    content: String!
    author: User! @belongsTo
    categories: [Category!] @belongsToMany
    images: [Image!]! @hasMany
    comments(
        "Limit the number of comments returned."
        limit: Int @limit
        "Order the comments."
        orderBy: [OrderByClause!] @orderBy
    ): [Comment!] @hasMany
    created_at: DateTime!
    updated_at: DateTime!
    published: Boolean!
    isFavorite: Boolean! @method(name: "isFavorite")
}

"A role for a user."
type Role @model(class: "App\\Models\\Roles") {
    id: ID!
    name: String!
    slug: String!
}

"A category for an article."
type Category {
    id: ID!
    name: String!
    slug: String!
}

"An image for an article."
type Image @model(class: "App\\Models\\Images") {
    id: ID!
    path: String!
    created_at: DateTime!
    updated_at: DateTime!
}

type Comment @model(class: "App\\Models\\Comments") {
    id: ID!
    content: String!
    created_at: DateTime!
    user: User! @belongsTo
    article: Article! @belongsTo
}

"Defines the queries available to the client."
type Query {
    "Find all published articles, paginated."
    publishedArticles(
        "Filter by category ID."
        category_id: ID @scope(name: "categoryId")
    ): [Article!]! @paginate(defaultCount: 10) @where(key: "published", value: true) @orderBy(column: "created_at", direction: DESC)

    "Find all article by a specific user, paginated"
    articlesByUser(userID: ID! @eq(key: "author_id")): [Article!] @paginate(defaultCount: 10)

    "Find a user."
    user(id: ID! @eq): User @find @guard(with: ["sanctum"])

    "Me"
    me: User @auth

    "Get All User Data."
    getUserData(id: ID! @eq): User @find

    "Get All articles for a user"
    userArticles: User @auth @guard(with: ["sanctum"])

    "Get Article by Id"
    article(id: ID! @eq): Article @find

    "Get All Categories"
    getCategories: [Category!]! @all

    "Search in Articles"
    searchArticles(search: String! @scope(name: "search")): [Article!]! @paginate(defaultCount: 10)

    "Get Favorite Articles for User"
    getFavoriteArticles: User @auth @guard(with: ["sanctum"])
}

"A token response for authentication."
type AuthPayload {
    token: String!
    user: User!
}


"Defines the mutations available to the client."
type Mutation {
    login(email: String!, password: String!): AuthPayload @field(resolver: "App\\GraphQL\\Mutations\\Login")

    createArticle(title: String!, content: String!, categoryIds: [ID!], images: [Upload!], publish: Boolean): Article
    @field(resolver: "App\\GraphQL\\Mutations\\CreateArticle")
    @guard(with: ["sanctum", "admin"])
    @admin

    editArticle(id: ID!, title: String, content: String, categoryIds: [ID!], images: [Upload]): Article
    @field(resolver: "App\\GraphQL\\Mutations\\EditArticle")
    @guard(with: ["sanctum", "admin"])
    @admin

    addComment(articleId: ID!, content: String!): Comment
    @field(resolver: "App\\GraphQL\\Mutations\\AddComment")
    @guard(with: ["sanctum"])

    deleteImage(id: ID!): Image
    @field(resolver: "App\\GraphQL\\Mutations\\DeleteImage")
    @guard(with: ["sanctum"])

    addUser(username: String!, password: String!, passwordRepeat: String!, email: String!): User
    @field(resolver: "App\\GraphQL\\Mutations\\AddUser")

    addCategory(name: String!): Category
    @field(resolver: "App\\GraphQL\\Mutations\\AddCategory")

    deleteCategory(id: ID!): Category
    @field(resolver: "App\\GraphQL\\Mutations\\DeleteCategory")

    addFavoriteArticle(articleId: ID!): Article
    @field(resolver: "App\\GraphQL\\Mutations\\AddFavoriteArticle")

    addLastReadArticle(articleId: ID!): Article
    @field(resolver: "App\\GraphQL\\Mutations\\AddLastReadArticle")

    updatePassword(oldPassword: String!, password: String!, passwordRepeat: String!): User
    @field(resolver: "App\\GraphQL\\Mutations\\UpdatePassword")

    updateEmail(email: String!): User
    @field(resolver: "App\\GraphQL\\Mutations\\UpdateEmail")

    togglePublishStatus(articleId: ID!, publish: Boolean): Article
    @field(resolver: "App\\GraphQL\\Mutations\\PublishStatusArticle")
}
